// Copyright (c) Microsoft. All rights reserved.

using System.Text.Json.Serialization;
using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.AI;
using WorkflowRouteBuilder = Microsoft.Agents.AI.Workflows.RouteBuilder;

namespace AgentWebChat.AgentHost.Workflows;

/// <summary>
/// Factory class for building the Marketing Content Workflow using the framework Workflow type.
/// This workflow implements a Human-in-the-Loop (HITL) pattern with:
/// 1. Writer step - AI generates initial marketing content
/// 2. Reviewer step - AI reviews and refines the content
/// 3. Approval step - Human approves, rejects, or requests revisions (via RequestPort)
/// </summary>
public static class MarketingWorkflowFactory
{
    public const string WorkflowName = "marketing-content";

    /// <summary>
    /// Builds the marketing content workflow using the framework Workflow type.
    /// </summary>
    /// <param name="chatClient">The chat client for AI interactions.</param>
    /// <returns>A configured Workflow instance.</returns>
    public static Workflow Build(IChatClient chatClient)
    {
        // Create executors
        var writer = new WriterExecutor(chatClient);
        var reviewer = new ReviewerExecutor(chatClient);
        var outputExecutor = new OutputExecutor();

        // Create the approval request port for human-in-the-loop
        var approvalPort = RequestPort.Create<MarketingApprovalRequest, MarketingApprovalResponse>("approval");

        // Build workflow with conditional routing based on approval decision
        // Flow: Writer -> Reviewer -> ApprovalPort -> (approve: Output, revise: Writer, reject: Output)
        return new WorkflowBuilder(writer)
            .AddEdge(writer, reviewer)
            .AddEdge(reviewer, approvalPort)
            .AddSwitch(approvalPort, sw => sw
                .AddCase<MarketingApprovalResponse>(r => r?.Decision == ApprovalDecision.Approve, outputExecutor)
                .AddCase<MarketingApprovalResponse>(r => r?.Decision == ApprovalDecision.Revise, writer)
                .AddCase<MarketingApprovalResponse>(r => r?.Decision == ApprovalDecision.Reject, outputExecutor))
            .WithOutputFrom(outputExecutor)
            .WithName(WorkflowName)
            .WithDescription("A Human-in-the-Loop workflow for creating and approving marketing content with AI-assisted writing and review steps.")
            .Build();
    }
}

// ============ Workflow Data Types ============

/// <summary>
/// Initial request to create marketing content.
/// </summary>
public sealed class MarketingContentInput
{
    [JsonPropertyName("topic")]
    public string? Topic { get; init; }

    [JsonPropertyName("targetAudience")]
    public string? TargetAudience { get; init; }

    [JsonPropertyName("tone")]
    public string? Tone { get; init; }
}

/// <summary>
/// Content generated by the writer or reviewer.
/// </summary>
public sealed class MarketingContent
{
    [JsonPropertyName("content")]
    public string Content { get; init; } = string.Empty;

    [JsonPropertyName("step")]
    public string Step { get; init; } = string.Empty;

    [JsonPropertyName("version")]
    public int Version { get; init; } = 1;

    [JsonPropertyName("qualityScore")]
    public double? QualityScore { get; init; }

    [JsonPropertyName("reviewerNotes")]
    public string? ReviewerNotes { get; init; }
}

/// <summary>
/// Request sent to human for approval decision.
/// </summary>
public sealed class MarketingApprovalRequest
{
    [JsonPropertyName("content")]
    public string Content { get; init; } = string.Empty;

    [JsonPropertyName("reviewerNotes")]
    public string? ReviewerNotes { get; init; }

    [JsonPropertyName("version")]
    public int Version { get; init; }

    [JsonPropertyName("options")]
    public IReadOnlyList<string> Options { get; init; } = ["approve", "revise", "reject"];
}

/// <summary>
/// Human approval response.
/// </summary>
public sealed class MarketingApprovalResponse
{
    [JsonPropertyName("decision")]
    public ApprovalDecision Decision { get; init; }

    [JsonPropertyName("feedback")]
    public string? Feedback { get; init; }
}

/// <summary>
/// Final output of the workflow.
/// </summary>
public sealed class MarketingWorkflowOutput
{
    [JsonPropertyName("content")]
    public string Content { get; init; } = string.Empty;

    [JsonPropertyName("status")]
    public string Status { get; init; } = string.Empty;

    [JsonPropertyName("totalVersions")]
    public int TotalVersions { get; init; }

    [JsonPropertyName("feedback")]
    public string? Feedback { get; init; }
}

/// <summary>
/// Approval decision enum.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ApprovalDecision
{
    Approve,
    Revise,
    Reject
}

// ============ Shared Workflow State ============

/// <summary>
/// Shared state for tracking workflow progress across iterations.
/// </summary>
internal sealed class MarketingWorkflowState
{
    public int Version { get; set; } = 1;
    public string? OriginalTopic { get; set; }
    public string? LastContent { get; set; }
    public string? LastFeedback { get; set; }
    public ApprovalDecision? LastDecision { get; set; }
}

internal static class MarketingWorkflowStateKeys
{
    public const string Scope = "MarketingWorkflowScope";
    public const string Key = "state";
}

// ============ Custom Executors ============

/// <summary>
/// Executor that generates marketing content based on input or revision feedback.
/// </summary>
internal sealed class WriterExecutor : Executor
{
    private readonly AIAgent _agent;

    public WriterExecutor(IChatClient chatClient) : base("writer")
    {
        this._agent = new ChatClientAgent(
            chatClient,
            name: "ContentWriter",
            instructions: """
                You are a skilled marketing content writer. Create clear, engaging marketing content.
                If you receive revision feedback, carefully revise the content to address all concerns.
                Always maintain a professional yet engaging tone.
                Output only the marketing content without any meta-commentary.
                """
        );
    }

    protected override WorkflowRouteBuilder ConfigureRoutes(WorkflowRouteBuilder routeBuilder) =>
        routeBuilder
            .AddHandler<MarketingContentInput, MarketingContent>(this.HandleInitialRequestAsync)
            .AddHandler<MarketingApprovalResponse, MarketingContent>(this.HandleRevisionRequestAsync);

    /// <summary>
    /// Handles the initial content creation request.
    /// </summary>
    private async ValueTask<MarketingContent> HandleInitialRequestAsync(
        MarketingContentInput input,
        IWorkflowContext context,
        CancellationToken cancellationToken = default)
    {
        var state = await context.ReadOrInitStateAsync(
            MarketingWorkflowStateKeys.Key,
            () => new MarketingWorkflowState { OriginalTopic = input.Topic },
            MarketingWorkflowStateKeys.Scope,
            cancellationToken);

        var prompt = $"""
            Create marketing content for the following:
            Topic: {input.Topic ?? "general marketing"}
            Target Audience: {input.TargetAudience ?? "general audience"}
            Tone: {input.Tone ?? "professional and engaging"}

            Include:
            - A compelling headline
            - Main body content (2-3 paragraphs)
            - Key benefits or features (as bullet points)
            - A call to action
            """;

        var response = await this._agent.RunAsync(prompt, cancellationToken: cancellationToken);
        var content = response.Text ?? string.Empty;

        state.LastContent = content;
        await context.QueueStateUpdateAsync(MarketingWorkflowStateKeys.Key, state, MarketingWorkflowStateKeys.Scope, cancellationToken);

        return new MarketingContent
        {
            Content = content,
            Step = "writer",
            Version = state.Version
        };
    }

    /// <summary>
    /// Handles revision requests based on feedback.
    /// </summary>
    private async ValueTask<MarketingContent> HandleRevisionRequestAsync(
        MarketingApprovalResponse approvalResponse,
        IWorkflowContext context,
        CancellationToken cancellationToken = default)
    {
        var state = await context.ReadStateAsync<MarketingWorkflowState>(
            MarketingWorkflowStateKeys.Key,
            MarketingWorkflowStateKeys.Scope,
            cancellationToken) ?? new MarketingWorkflowState();

        state.Version++;
        state.LastFeedback = approvalResponse.Feedback;

        var prompt = $"""
            Revise the following marketing content based on this feedback:

            FEEDBACK: {approvalResponse.Feedback ?? "General improvements needed"}

            ORIGINAL CONTENT:
            {state.LastContent}

            Please address all feedback points while maintaining the overall message and tone.
            """;

        var response = await this._agent.RunAsync(prompt, cancellationToken: cancellationToken);
        var content = response.Text ?? string.Empty;

        state.LastContent = content;
        await context.QueueStateUpdateAsync(MarketingWorkflowStateKeys.Key, state, MarketingWorkflowStateKeys.Scope, cancellationToken);

        return new MarketingContent
        {
            Content = content,
            Step = "writer",
            Version = state.Version
        };
    }
}

/// <summary>
/// Executor that reviews marketing content and adds suggestions.
/// </summary>
internal sealed class ReviewerExecutor : Executor<MarketingContent, MarketingApprovalRequest>
{
    private readonly AIAgent _agent;

    public ReviewerExecutor(IChatClient chatClient) : base("reviewer")
    {
        this._agent = new ChatClientAgent(
            chatClient,
            name: "ContentReviewer",
            instructions: """
                You are a marketing content reviewer. Review the content and provide:
                1. A quality score (1-10)
                2. Specific strengths
                3. Areas for improvement
                4. Overall recommendation

                Be constructive and specific in your feedback.
                Format your review clearly with sections.
                """
        );
    }

    public override async ValueTask<MarketingApprovalRequest> HandleAsync(
        MarketingContent message,
        IWorkflowContext context,
        CancellationToken cancellationToken = default)
    {
        var prompt = $"""
            Review the following marketing content:

            {message.Content}

            Provide a structured review with:
            - Quality Score (1-10)
            - Strengths
            - Areas for Improvement
            - Recommendation
            """;

        var response = await this._agent.RunAsync(prompt, cancellationToken: cancellationToken);
        var reviewerNotes = response.Text ?? string.Empty;

        // Update state with reviewed content
        var state = await context.ReadStateAsync<MarketingWorkflowState>(
            MarketingWorkflowStateKeys.Key,
            MarketingWorkflowStateKeys.Scope,
            cancellationToken) ?? new MarketingWorkflowState();

        // Return approval request for human review
        return new MarketingApprovalRequest
        {
            Content = message.Content,
            ReviewerNotes = reviewerNotes,
            Version = message.Version,
            Options = ["approve", "revise", "reject"]
        };
    }
}

/// <summary>
/// Executor that produces the final output based on the approval decision.
/// </summary>
internal sealed class OutputExecutor : Executor<MarketingApprovalResponse, MarketingWorkflowOutput>
{
    public OutputExecutor() : base("output")
    {
    }

    public override async ValueTask<MarketingWorkflowOutput> HandleAsync(
        MarketingApprovalResponse message,
        IWorkflowContext context,
        CancellationToken cancellationToken = default)
    {
        var state = await context.ReadStateAsync<MarketingWorkflowState>(
            MarketingWorkflowStateKeys.Key,
            MarketingWorkflowStateKeys.Scope,
            cancellationToken) ?? new MarketingWorkflowState();

        var status = message.Decision switch
        {
            ApprovalDecision.Approve => "approved",
            ApprovalDecision.Reject => "rejected",
            _ => "unknown"
        };

        var output = new MarketingWorkflowOutput
        {
            Content = state.LastContent ?? string.Empty,
            Status = status,
            TotalVersions = state.Version,
            Feedback = message.Feedback
        };

        await context.YieldOutputAsync(output, cancellationToken);

        return output;
    }
}
